package day13;	//예외 메소드를 전부 묶어 놓은 것!

public class ExceptionError1 {
	
	public static void main(String[] args) {
	
	try {
		System.out.println("매개변수로 받은 두 개의 값");
		int a = Integer.parseInt(args[0]);	//문자열 값을 정수로 변환
		int b = Integer.parseInt(args[1]);
		System.out.println(" a = "+ a +" b ="+ b);
		System.out.println(" a를  b로 나눈 몫 = " + (a/b));
		System.out.println("나눗셈이 원활히 수행되었습니다.");
	}catch(ArithmeticException e) {
		System.out.println("============================");
		System.out.println("ArithmeticException 처리 루틴 : "); //정수를 0으로 나눌 때 발생
		System.out.println(e + "예외 발생");
	}catch(ArrayIndexOutOfBoundsException e) {
		System.out.println("============================");
		System.out.println("ArrayIndexOutOfBoundsException 처리 루틴 : "); //배열의 범위를 벗어난 접근 시 발생
		System.out.println(e + "예외 발생");
	}catch(NumberFormatException e) {
		System.out.println("============================");
		System.out.println("NumberFormatException 처리 루틴 : "); //문자열이 나타내는 숫자와 일치하지 않는 타입의 숫자로 변환 시 발생
		System.out.println(e + "예외 발생");
	}catch(Exception e) {
		System.out.println("============================");
		System.out.println("알 수 없는 문제가 발생했습니다. ");
		System.out.println(e.toString());
	}finally {
		System.out.println("============================");
		System.out.println("예외 처리를 끝내고 finally 블럭을 수행합니다.");
	}
	System.out.println("나머지 모듈 정상 작동!!!");
}
}